---
- name: Restart SystemBanner
  ansible.windows.win_shell: |
    $procs = Get-Process -Name SystemBanner -ErrorAction SilentlyContinue
    if ($procs) { $procs | Stop-Process -Force }
  listen: Restart SystemBanner
